### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by juhamust** [SC5/gulp-bobrsass-boilerplate#12]
The dependencies defined in package `package.json` are getting old. 

For example: I was hunting down the issue in a project using the boilerplate. The issue was related to `gulp-inject` usage, and I finally noticed the boilerplate comes with version 0.4.1 whereas 1.0.2 is current (and comes with functionality I was expecting to have based on project documentation)

Thus, dependencies should be updated.

**Comment by laurisvan** [comment]
Pull request #33 should fix this. I wonder why it wasn't autoreferenced here, regardless of the fixes label and the issue number...
