### ISSUE TITLE
No Express?

### ISSUE THREAD

**Issue by kennu** [SC5/gulp-bobrsass-boilerplate#29]
Should there be an Express server module included so the web app can be served, and APIs and middlewares like Passport added to it? Seems particularly useful for Docker builds..

**Comment by laurisvan** [comment]
While a server boilerplate would be an useful thing, wouldn't it work better as a separate project? I'd like to mix this frontend boilerplate (that only depends on a static web server and perhaps URL rewrites for frameworks that use pushstate). In the end, the backends are maybe even more varied than frontends...

That way we could mix and match whatever servers we will need. Would it work ok for you?

**Comment by kennu** [comment]
Sounds good, if there is a simple documented way to include the server module in your own project.
