### ISSUE TITLE
Angular.js structure for services, filters, data models etc

### ISSUE THREAD

**Issue by kennu** [SC5/gulp-bobrsass-boilerplate#30]
It seems to be unclear how Angular.js application files should be structured under src. I would recommend the structure used by Angular-Fullstack, which groups all "article" related files under client/app/article:

    article.controller.js
    article.controller.spec.js
    article.html
    article.js
    article.scss

Additionally it groups data models (services) and filters under client/components/article:

    article.service.js
    articleurl.filter.js

Following a given structure like this, it's very easy to build a coherently structured web app, and to automatically inject all the controllers, routes, services and filters into index.html.

**Comment by laurisvan** [comment]
Pull request #36 should fix this. I wonder why it wasn't autoreferenced here, regardless of the fixes label and the issue number...
